-- Select cafe lunch specials for a nut-free quick-service display image.
-- Source table: menu_items in menu_inventory.sqlite.
-- Required filters:
--   meal_type = 'lunch'
--   status = 'active'
--   available = 1
--   stock > 10
--   contains_nuts = 0
--   prep_minutes <= 10
--   service_window = 'weekday_lunch'
-- Sort order:
--   margin_score DESC
--   prep_minutes ASC
--   price_usd ASC
-- Select top 3.
-- Suggested image copy: Nut-free quick lunch specials
